# Generated by Django 6.0.6 on 2026-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('user', 'task', 'completed_date')},
        ),
    ]
